server:
  port: ${PORT:9999}
  context-path: ${CONTEXTPATH:/spring-boot}
  session:
    timeout: 5

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.113.9.38:3306/finance?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 64
          plan_parameter_metadata_max_size: 32

sas:
  queue:
    name: ${SAS.QUEUE.GENERIC:ActiveMQ.FINANCE.SAS}
