server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zk?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
