server:
  port: ${PORT:9999}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr([%-40.40logger{39}]){cyan} %4L - %m%n'
#  file: springBootDemo.log
spring:
  datasource:
        url: jdbc:mysql://localhost:3306/zk?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
mybatis-plus:
#  type-enums-package: org.zk.enums
#  type-handlers-package: org.zk.typehandlers
