server:
  port: ${PORT:9999}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr([%-40.40logger{39}]){cyan} %4L - %m%n'
#  file: springBootDemo.log

dubbo:
  application:
    name: demo-provider
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://10.200.4.74:2181
  scan:
    base-packages: org.zk.service
  consumer:
    retries: 0
    timeout: 60000000
